const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {render}=require('../docs/admin/email_traffic.js');
for(const input of [undefined,{available:false},{available:true}])assert.match(render(input,20),/미적용|불완전/);
const blank={available:true,timezone:'UTC',daily:[],editions:[],countries:[],devices:[]};
assert.match(render(blank,20),/기록이 없습니다/);
assert.doesNotMatch(render(blank,20),/집계 미적용/);
const data={...blank,daily:[{day:'2026-10-07',page:'samsung',views:3},{day:'2026-10-07',page:'sk_hynix',views:1}],editions:[{edition_day:'2026-10-06',edition_phase:'post_close',page:'samsung',views:3}],countries:[{country:'KR',views:3},{country:'unknown',views:1}],devices:[{device:'mobile',views:3},{device:'unknown',views:1}]};
let html=render(data,20);
for(const text of ['20.0%','삼성전자','SK하이닉스','대한민국','모바일','알 수 없음','마감 후','2026-10-06','UTC'])assert.ok(html.includes(text),text);
assert.ok(!html.includes('NaN'));
assert.match(render({...data,countries:undefined,devices:undefined},20),/추가 통계 미적용/);
assert.doesNotMatch(render(data,0),/Infinity|NaN/);
html=render({...data,daily:[{day:'<img src=x onerror=alert(1)>',page:'<script>',views:1}],countries:[{country:'<img>',views:1}],editions:[{edition_day:'<script>',edition_phase:'<img>',page:'<svg>',views:1}]},20);
assert.ok(!html.includes('<script>')&&!html.includes('<img')&&!html.includes('<svg>'));
assert.ok(html.includes('&lt;script&gt;'));
// 브라우저 전역 및 실제 관리자 렌더 연결을 함께 확인한다.
const ctx={};vm.runInNewContext(fs.readFileSync('docs/admin/email_traffic.js','utf8'),ctx);assert.equal(typeof ctx.EmailTraffic.render,'function');
const page=fs.readFileSync('docs/admin/index.html','utf8');
assert.ok(page.includes('id="email-traffic"'));
assert.ok(page.indexOf('src="email_traffic.js"')<page.indexOf('function render(data, days)'));
assert.match(page,/EmailTraffic\.render\(data\.emailTraffic,\s*periodViews\)/);
console.log('이메일 화면의 호환·빈 자료·비율·날짜·이스케이프·관리자 연결 검증 통과');
(async()=>{
  const element=()=>({value:'',innerHTML:'',textContent:'',style:{},parentNode:{style:{}},events:{},insertAdjacentHTML(){},setAttribute(){},appendChild(){},addEventListener(name,fn){this.events[name]=fn;}});
  const nodes=new Map([...page.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],element()]));
  const get=id=>{assert.ok(nodes.has(id),id);return nodes.get(id);};
  let body={totals:[],daily:[{day:'2026-10-07',page:'samsung',views:20,visitors:10}],emailTraffic:data};
  const requests=[];
  const context={Intl,EmailTraffic:{render},document:{getElementById:get,createElementNS:element,createElement:element},localStorage:{getItem(){return null;}},fetch:async(url,opts)=>{requests.push({url,opts});return {status:200,text:async()=>JSON.stringify(body)};}};
  const script=[...page.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('function render(data, days)'));
  vm.runInNewContext(script,context);
  get('token').value='private-token';get('days').value='7';
  get('f').events.submit({preventDefault(){}});await new Promise(r=>setImmediate(r));
  assert.equal(requests[0].opts.headers.Authorization,'Bearer private-token');
  assert.ok(requests[0].url.endsWith('/stats?days=7'));assert.ok(!requests[0].url.includes('private-token'));
  assert.equal(get('report').style.display,'block',get('msg').textContent);
  assert.match(get('email-traffic').innerHTML,/20.0%/);
  body={totals:[],daily:[]};get('f').events.submit({preventDefault(){}});await new Promise(r=>setImmediate(r));
  assert.equal(get('report').style.display,'block',get('msg').textContent);assert.match(get('email-traffic').innerHTML,/집계 미적용/);
  console.log('실제 관리자 조회 이벤트·인증 헤더·화면 갱신 검증 통과');
})().catch(e=>{console.error(e);process.exitCode=1;});
